/* eslint-disable import/no-anonymous-default-export */
export default {
    sliderData:[
        {
          id:1,
          mobilImg:`/images/delete/slide1.webp`,
          desktopImg:`/images/delete/slide1.webp`,
          title:`Kenan Doğulu Konseri`,
          url:`/konserler/kenan-doğulu-konseri-15912`,
          subtitle:`Küçük Çiftlikpark’ta`,
          subtitleUrl:`/mekan/kucuk-ciftlik-park`,
        },
        {
          id:2,
          mobilImg:`/images/delete/slide2.webp`,
          desktopImg:`/images/delete/slide2.webp`,
          title:`Emin Özal Konseri`,
          url:`/konserler/emin-özal-konseri-15911`,
          subtitle:`Fişekhane Grandpera`,
          subtitleUrl:`/mekan/sehir-mahallesi`,
        },
        {
          id:3,
          mobilImg:`/images/delete/slide3.webp`,
          desktopImg:`/images/delete/slide3.webp`,
          title:`Murat Uysal Konseri`,
          url:`/konserler/murat-uysal-konseri-15910`,
          subtitle:`26 Ağustos Cuma, 19:30`,
          subtitleUrl:``,
        }
      ],
    
      populerData: [
        {
          id:1,
          mobilImg:`/images/delete/p1.webp`,
          desktopImg:`/images/delete/p1.webp`,
          title:`Kenan Doğulu Konseri`,
          url:`/konserler/kenan-doğulu-konseri-15912`,
          date:`24 Mayıs`,
          venueUrl:`/mekan/kucuk-ciftlikpark`,
          venueName:`Küçük Çiftlikpark`,
          venueId:1,
          city:`İstanbul`,
          variant:"populer"
        },
        {
          id:2,
          mobilImg:`/images/delete/p2.webp`,
          desktopImg:`/images/delete/p2.webp`,
          title:`Can Bonomo 100.Yıl Konser`,
          url:`/konserler/emin-özal-konseri-15911`,
          date:`25 Mayıs`,
          venueUrl:`/mekan/kucuk-ciftlikpark`,
          venueName:`Fişekhane Grandpera`,
          venueId:2,
          city:`Ankara`,
          variant:"populer"
        },
        {
          id:3,
          mobilImg:`/images/delete/p3.webp`,
          desktopImg:`/images/delete/p3.webp`,
          title:`Murat Uysal Konseri`,
          url:`/konserler/murat-uysal-konseri-15910`,
          date:`26 Mayıs`,
          venueUrl:`/mekan/kucuk-ciftlikpark`,
          venueName:`Küçük Çiftlikpark`,
          venueId:3,
          city:`İstanbul`,
          variant:"populer"
        },
        {
          id:4,
          mobilImg:`/images/delete/p4.webp`,
          desktopImg:`/images/delete/p4.webp`,
          title:`Bursa Nilüfer Müzil Festivali`,
          url:`/konserler/murat-uysal-konseri-15910`,
          date:`27 Mayıs`,
          venueUrl:`/mekan/kucuk-ciftlikpark`,
          venueName:`Küçük Çiftlikpark`,
          venueId:4,
          city:`Bursa`,
          variant:"populer"
        },
        {
          id:5,
          mobilImg:`/images/delete/p5.webp`,
          desktopImg:`/images/delete/p5.webp`,
          title:`Hadise Konseri`,
          url:`/konserler/murat-uysal-konseri-15910`,
          date:`28 Mayıs`,
          venueUrl:`/mekan/kucuk-ciftlikpark`,
          venueName:`Küçük Çiftlikpark`,
          venueId:5,
          city:`Eskişehir`,
        }
      ],
      MostExpectedData:[
        {
          id:1,
          mobilImg:`/images/delete/p5.webp`,
          desktopImg:`/images/delete/p5.webp`,
          title:`Justin Bieber`,
          url:`/konserler/kenan-doğulu-konseri-15912`,
          date:`24 Mayıs`,
          venueUrl:`/mekan/kucuk-ciftlikpark`,
          venueName:`Küçük Çiftlikpark`,
          venueId:1,
          city:`İstanbul`,
        },
        {
          id:1,
          mobilImg:`/images/delete/p4.webp`,
          desktopImg:`/images/delete/p4.webp`,
          title:`Ariana Dua Grande`,
          url:`/konserler/kenan-doğulu-konseri-15912`,
          date:`24 Mayıs`,
          venueUrl:`/mekan/kucuk-ciftlikpark`,
          venueName:`Küçük Çiftlikpark`,
          venueId:1,
          city:`İstanbul`,
        },
        {
          id:1,
          mobilImg:`/images/delete/p6.webp`,
          desktopImg:`/images/delete/p6.webp`,
          title:`Nilüfer Müzik Festivali`,
          url:`/konserler/kenan-doğulu-konseri-15912`,
          date:`24 Mayıs`,
          venueUrl:`/mekan/kucuk-ciftlikpark`,
          venueName:`Küçük Çiftlikpark`,
          venueId:1,
          city:`İstanbul`,
        },
      ]
}