export default {
    homeData: {
        sliderData: [
            {
                id: 1,
                image: `/images/delete/slide1.webp`,
                name: `Kenan Doğulu Konseri`,
                url: `/konser/kenan-doğulu-konseri-15912`,
                subtitle: `Küçük Çiftlikpark’ta`,
            },
            {
                id: 2,
                image: `/images/delete/slide2.webp`,
                name: `Emin Özal Konseri`,
                url: `/konser/emin-özal-konseri-15911`,
                subtitle: `Fişekhane Grandpera`,
            },
            {
                id: 3,
                image: `/images/delete/slide3.webp`,
                name: `Murat Uysal Konseri`,
                url: `/konser/murat-uysal-konseri-15910`,
                subtitle: `26 Ağustos Cuma, 19:30`,
            },
            {
                id: 4,
                image: `/images/delete/slide4.webp`,
                name: `Kenan Doğulu Konseri`,
                url: `/konser/kenan-doğulu-konseri-15912`,
                subtitle: `Küçük Çiftlikpark’ta`,
            },
            {
                id: 5,
                image: `/images/delete/slide5.webp`,
                name: `Emin Özal Konseri`,
                url: `/konser/emin-özal-konseri-15911`,
                subtitle: `Fişekhane Grandpera`,
            },
            {
                id: 6,
                image: `/images/delete/slide6.webp`,
                name: `Murat Uysal Konseri`,
                url: `/konser/murat-uysal-konseri-15910`,
                subtitle: `26 Ağustos Cuma, 19:30`,
            },
        ],
        popularEvents: [
            {
                id: 1,
                image: "/images/delete/p1.webp",
                name: "Kenan Doğulu Konseri",
                url: "/konser/kenan-doğulu-konseri-15912",
                date: "1724686200",
                venue: "Fişekhane Grandpera",
                venueUrl: "/mekan/fisekhane-grandpera",
                city: "İstanbul",
            },
            {
                id: 2,
                image: "/images/delete/p2.webp",
                name: "Tarkan Konseri",
                url: "/konser/tarkan-konseri-15913",
                date: "1725291000",
                venue: "Kanyon AVM",
                venueUrl: "/mekan/kanyon-avm",
                city: "Ankara",
            },
            {
                id: 3,
                image: "/images/delete/p3.webp",
                name: "Sezen Aksu Konseri",
                url: "/konser/sezen-aksu-konseri-15914",
                date: "1725895800",
                venue: "Zorlu Center",
                venueUrl: "/mekan/zorlu-center",
                city: "İzmir",
            },
            {
                id: 4,
                image: "/images/delete/p4.webp",
                name: "Sertab Erener Konseri",
                url: "/konser/sertab-erener-konseri-15915",
                date: "1726500600",
                venue: "Akmerkez",
                venueUrl: "/mekan/akmerkez",
                city: "Bursa",
            },
            {
                id: 5,
                image: "/images/delete/p5.webp",
                name: "Teoman Konseri",
                url: "/konser/teoman-konseri-15916",
                date: "1727105400",
                venue: "İstinye Park",
                venueUrl: "/mekan/istinye-park",
                city: "Antalya",
            },
            {
                id: 6,
                image: "/images/delete/p6.webp",
                name: "Şebnem Ferah Konseri",
                url: "/konser/sebnem-ferah-konseri-15917",
                date: "1727710200",
                venue: "Mall of Istanbul",
                venueUrl: "/mekan/mall-of-istanbul",
                city: "Adana",
            }
        ],
        mostExpectedEvents: [
            {
                id: 1,
                image: "/images/delete/p5.webp",
                name: "Justin Bieber",
                url: "/konser/kenan-doğulu-konseri-15912",
                date: "1724686200",
                venue: "Fişekhane Grandpera",
                venueUrl: "/mekan/fisekhane-grandpera",
                city: "İstanbul",
            },
            {
                id: 2,
                image: "/images/delete/p4.webp",
                name: "Ariana Grande Show",
                url: "/konser/tarkan-konseri-15913",
                date: "1725291000",
                venue: "Kanyon AVM",
                venueUrl: "/mekan/kanyon-avm",
                city: "Ankara",
            },
            {
                id: 3,
                image: "/images/delete/p3.webp",
                name: "Nilüfer Müzik Festivali",
                url: "/konser/sezen-aksu-konseri-15914",
                date: "1725895800",
                venue: "Zorlu Center",
                venueUrl: "/mekan/zorlu-center",
                city: "İzmir",
            },
            {
                id: 4,
                image: "/images/delete/p2.webp",
                name: "Hayko Cepkin",
                url: "/konser/sertab-erener-konseri-15915",
                date: "1726500600",
                venue: "Akmerkez",
                venueUrl: "/mekan/akmerkez",
                city: "Bursa",
            }
        ],
        popularArtist:[
            {
                "id": 1,
                "image": "/images/delete/ar1.webp",
                "name": "Kenan Doğulu",
                "url": "/sanatci/kenan-dogulu-15912",
                "isFollow": false,
                "followerCount": 152569
              },
              {
                "id": 2,
                "image": "/images/delete/ar2.webp",
                "name": "Tarkan",
                "url": "/sanatci/tarkan-15913",
                "isFollow": false,
                "followerCount": 200432
              },
              {
                "id": 3,
                "image": "/images/delete/ar3.webp",
                "name": "Sezen Aksu",
                "url": "/sanatci/sezen-aksu-15914",
                "isFollow": false,
                "followerCount": 180987
              },
              {
                "id": 4,
                "image": "/images/delete/ar4.webp",
                "name": "Hadise",
                "url": "/sanatci/hadise-15915",
                "isFollow": false,
                "followerCount": 160543
              },
              {
                "id": 5,
                "image": "/images/delete/ar5.webp",
                "name": "Murat Boz",
                "url": "/sanatci/murat-boz-15916",
                "isFollow": false,
                "followerCount": 170321
              },
              {
                "id": 6,
                "image": "/images/delete/ar6.webp",
                "name": "Sıla",
                "url": "/sanatci/sila-15917",
                "isFollow": false,
                "followerCount": 155678
              }, {
                "id": 7,
                "image": "/images/delete/ar1.webp",
                "name": "Kenan Doğulu",
                "url": "/sanatci/kenan-dogulu-15912",
                "isFollow": false,
                "followerCount": 152569
              },
              {
                "id": 8,
                "image": "/images/delete/ar2.webp",
                "name": "Tarkan",
                "url": "/sanatci/tarkan-15913",
                "isFollow": false,
                "followerCount": 200432
              },
              {
                "id": 9,
                "image": "/images/delete/ar3.webp",
                "name": "Sezen Aksu",
                "url": "/sanatci/sezen-aksu-15914",
                "isFollow": false,
                "followerCount": 180987
              },
              {
                "id": 10,
                "image": "/images/delete/ar4.webp",
                "name": "Hadise",
                "url": "/sanatci/hadise-15915",
                "isFollow": false,
                "followerCount": 160543
              },
              {
                "id": 11,
                "image": "/images/delete/ar5.webp",
                "name": "Murat Boz",
                "url": "/sanatci/murat-boz-15916",
                "isFollow": false,
                "followerCount": 170321
              },
              {
                "id": 12,
                "image": "/images/delete/ar6.webp",
                "name": "Sıla",
                "url": "/sanatci/sila-15917",
                "isFollow": false,
                "followerCount": 155678
              }
        ],
        favoriteEvents: [
            {
                id: 1,
                image: "/images/delete/p1.webp",
                name: "Kenan Doğulu Konseri",
                url: "/konser/kenan-doğulu-konseri-15912",
                date: "1724686200",
                venue: "Fişekhane Grandpera",
                venueUrl: "/mekan/fisekhane-grandpera",
                city: "İstanbul",
            },
            {
                id: 2,
                image: "/images/delete/p2.webp",
                name: "Tarkan Konseri",
                url: "/konser/tarkan-konseri-15913",
                date: "1725291000",
                venue: "Kanyon AVM",
                venueUrl: "/mekan/kanyon-avm",
                city: "Ankara",
            },
            {
                id: 3,
                image: "/images/delete/p3.webp",
                name: "Sezen Aksu Konseri",
                url: "/konser/sezen-aksu-konseri-15914",
                date: "1725895800",
                venue: "Zorlu Center",
                venueUrl: "/mekan/zorlu-center",
                city: "İzmir",
            },
            {
                id: 4,
                image: "/images/delete/p4.webp",
                name: "Sertab Erener Konseri",
                url: "/konser/sertab-erener-konseri-15915",
                date: "1726500600",
                venue: "Akmerkez",
                venueUrl: "/mekan/akmerkez",
                city: "Bursa",
            },
            {
                id: 5,
                image: "/images/delete/p5.webp",
                name: "Teoman Konseri",
                url: "/konser/teoman-konseri-15916",
                date: "1727105400",
                venue: "İstinye Park",
                venueUrl: "/mekan/istinye-park",
                city: "Antalya",
            },
            {
                id: 6,
                image: "/images/delete/p6.webp",
                name: "Şebnem Ferah Konseri",
                url: "/konser/sebnem-ferah-konseri-15917",
                date: "1727710200",
                venue: "Mall of Istanbul",
                venueUrl: "/mekan/mall-of-istanbul",
                city: "Adana",
            }
        ],
        tagCloud: [
            {
              "id": 1,
              "name": "Rap & Hiphop",
              "isFollow": false,
            },
            {
              "id": 2,
              "name": "Pop",
              "isFollow": false,
            },
            {
              "id": 3,
              "name": "Arabeks",
              "isFollow": false,
            },
            {
              "id": 4,
              "name": "Rock",
              "isFollow": false,
            },
            {
              "id": 5,
              "name": "Senfoni",
              "isFollow": false,
            },
            {
              "id": 6,
              "name": "Festival",
              "isFollow": false,
            },
          ],
    }
}