import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gozat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-body bg-primary-bg min-h-screen bg-no-repeat dark:bg-gray-200 dark:text-black text-white bg-cover ${inter.className}`}>
        <Header />
        <main className="px-2 flex flex-col gap-2 lg:gap-5 lg:px-0">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
